let quotes=[
	'Basilikakana',
	'Pho-keitto',
	'Uunibataatteja ja tahinikastike',
	'Munacurry',
	'Caesar-salaatti',
	'Katkarapu-sahramipasta',
	'Pasta carbonara',
	'Borsch-keitto',
	'Aloo gobi',
	'Kana + kermaperunat',
	'Orzovuoka',
	'Tattipasta',
	'Pinaattiletut',
	'Pad thai',
	'Uunimakkara ja muusi',
	'Lohikeitto',
	'Silakkapihvit',
	'Seljanka',
	'Lasagne',
	'Pitaleivät',
	'Tortillat',
	'Nachoplatter',
	'Kung pao',
	'Mapo-tofu',
	'Karhuntassutofu',
	'Kanakeitto',
	'Kreikkalainen salaatti',
	'Maalaissalaatti',
	'Lämmin vuohenjuustosalaatti',
	'Juuresfetasalaatti',
	'Lämpimät voileivät',
	'Chili con carne',
	'Kukkoa viinissä',
	'Smetanalohi',
	'Piparjuurisilakat',
	'Tomaattisilakat',
	'Matikkakeitto',
	'Hirvikeitto',
	'Blinit',
	'Pannusiika',
	'Juustofondue',
	'Uunikurpitsat ja tahinikastike',
	'Mejadrean-lohtupata',
	'Kanaa ja maa-artisokkaa',
	'Kaalilaatikko',
	'Kaalikääryleet',
	'Alsacen kaalikeitto ja kuorrutetutu juustopatongit',
	'Peruna-purjo-sosekeitto',
	'Maa-artisokkakeitto',
	'Makkara-sipuli-risotto',
	'Sienirisotto',
	'Kurpitsa-gorgonzola-risotto',
	'Pizza',
	'Calzone',
	'Satay-tofu',
	'Butter-paneer',
	'Intialainen linssikastike',
	'Ranskalainen linssipata',
	'Lyonin kana',
	'Chevize',
	'Lindströminpihvi',
	'Hauki-Wallenbergit',
	'Hauki-kvenellit',
	'Kalamurekepihvit',
	'Tonnikalacanneloni',
	'Munakoiso-puhvelimozzarella-canneloni',
	'Inkivääripasta',
	'Munakoisofusilli',
	'Burgerit',
	'Hodarit',
	'Lammas-tagine',
	'Kurpitsa-kikherne-tagine',
	'Falafelit',
	'Raviolit',
	'Salvia-aurajuusto-pasta',
	'Mascarponepasta',
	'Tonnikalapasta',
	'Feta-ohratto',
	'Savulohipasta',
	'Uuniperunat ja lohitäyte',
	'Schnitzel ja perunaa',
	'Makaronilaatikko',
	'Kinkkukiusaus',
	'Broiler-kiusaus',
	'Savulohilaatikko',
	'Tatti-kana-pastavuoka jossa vermuttia',
	'Puglian pannu',
	'Parsarisotto',
	'Paistettu riisi',
	'Saksanpähkinä-sitruuna-pasta',
	'Pähkinä-kana',
	'Moussakka',
	'Kesäkeitto',
	'Suppilovahvero-bolognese',
	'Sienipiirakka',
	'Savulohiriisipiirakka',
	'Feta-pinaattipiirakka',
	'Kukkakaali-gruyere-gratiini',
	'Kanttarellikeitto',
	'Uunumunakoisot ja couscous-salaatti',
];

function displayQuote(){
    //create an index of a random number 
    //convert it into between 0 to length of quotes[]
    let index=Math.floor(Math.random()*quotes.length);
   
    //display the quote of that index
    let div=document.querySelector('#quote');
    let quote=`<div class="card">
    <p>${quotes[index]}</p>
   </div>
    `;
    div.innerHTML=quote;
    
}
